ftw/events/configure.zcml, ftw/events/hooks.py, setup.py
plone.app.events replaces the start and end index by a RecurringDateIndex (before DateIndex) but it omits to reindex the new index. This causes the loss of the start and end index data of every content. So we need to take care of reindexing the indexes.
Closes https://github.com/4teamwork/ftw.events/issues/5
=> Reindex index (start, end) when add-on is installed.

docs/HISTORY.txt, ftw/events/hooks.py, ftw/events/profiles/default/propertiestool.xml, ftw/events/profiles/default/types/ftw.events.EventFolder.xml
This PR together with PRs in `ftw.calendar` and `ftw.calendarexport` integrate `ftw.events` into the calendar.
`ftw.calendar`: https://github.com/4teamwork/ftw.calendar/pull/17
`ftw.calendarexport`: https://github.com/4teamwork/ftw.calendarexport/pull/5
=> ftw.calendar integration

docs/HISTORY.txt, ftw/events/contents/eventlistingblock.py
If i want to edit or delete a `EventListingBlock` plone throws an error because the values on the `filter_by_path` and `subjects` widgets are `None`.
It checks the value against the missing value of `[]`. `None != []` so it assumes it has a value. Tries to iterate over it and faceplants hard.
I couldn't reproduce this behaviour in a test. Not exactly sure why..
=> Fix bug where default value was None instad of [].

docs/HISTORY.txt, ftw/events/contents/eventfolder.py
We have the signature
``create_event_listing_block(event_folder, event=None)``,
but when we pass no event we got an AttributeError.
By using ``getSite`` instead of ``event.newParent`` we can avoid this error.
=> Fix AttributeError in create_event_listing_block

docs/HISTORY.txt, ftw/events/locales/de/LC_MESSAGES/ftw.events.po
The event listing block is not a set of events but only a listing of events, therefore the German translation "Veranstaltungen" is not accurate, "Auflistung von Veranstaltungen" is better.
=> Change German translation for event listing block.

docs/HISTORY.txt, ftw/events/profiles/default/types/Plone_Site.xml, ftw/events/upgrades/20160921161132_make_addable_on_plone_site/types/Plone_Site.xml, ftw/events/upgrades/20160921161132_make_addable_on_plone_site/upgrade.py
Also add a missing changelog entry.
Fixes #12 and #13 
I didn't add an upgrade-step as this would change existing policy configuration.
=> Make EventFolder and EventListingBlock addable on the Plone Site by default.

.gitignore, docs/HISTORY.txt, ftw/events/behaviors/configure.zcml, ftw/events/behaviors/location.py, ftw/events/browser/eventlisting.py, ftw/events/browser/eventlistingblock.py, ftw/events/configure.zcml, ftw/events/contents/eventpage.py, ftw/events/locales/de/LC_MESSAGES/ftw.events.po, ftw/events/locales/ftw.events.pot, ftw/events/profiles/default/types/ftw.events.EventPage.xml, ftw/events/tests/test_event_listing.py, ftw/events/tests/test_event_listingblock.py, ftw/events/tests/test_event_page.py, ftw/events/upgrades/20161017150500_remove_event_location_behavior/types/ftw.events.EventPage.xml, ftw/events/upgrades/20161017150500_remove_event_location_behavior/upgrade.py
In order to have structured location information the fields are split up into address title, street / number, ZIP and city.
The new fields are implemented in a new behavior. Using `plone.app.event`'s behavior is still possible.
=> split up location fields.

README.rst, docs/HISTORY.txt, ftw/events/behaviors/configure.zcml, ftw/events/behaviors/mopage.py, ftw/events/browser/configure.zcml, ftw/events/browser/mopage.py, ftw/events/browser/templates/mopage_events.pt, ftw/events/configure.zcml, ftw/events/lawgiver.zcml, ftw/events/permissions.zcml, ftw/events/testing.py, ftw/events/tests/__init__.py, ftw/events/tests/mopage_assets/lorem1.html, ftw/events/tests/mopage_assets/mopage.events.xml, ftw/events/tests/test_mopage_export.py, ftw/events/tests/test_mopage_trigger.py, ftw/events/tests/utils.py, setup.py
Add mopage support for events, copied from `ftw.news`.
- `mopage.events.xml` view
- Mopage trigger behavior for event folders (ftw.publisher integration)
~~I have not included locations at all, because the event page only has one simple textfield for location and you can enter whatever you want, but the mopage API requires structured data (Street, ZIP, City) and we simply do not have this information at the moment.~~
🚧 use https://github.com/4teamwork/ftw.events/pull/16 for location.
=> Mopage support

docs/HISTORY.txt, ftw/events/browser/eventlistingblock.py, ftw/events/contents/eventlistingblock.py, ftw/events/profiles/default/metadata.xml, ftw/events/tests/__init__.py, ftw/events/upgrades/20161018162557_implement_ftw_referencewidget/metadata.xml, ftw/events/upgrades/20161018162557_implement_ftw_referencewidget/upgrade.py, setup.py
Implements the newest version of `ftw.referencewidget` to fix a bug in the event-listing-block which made the blocks break on a restart. 
Now there are no longer any objects linked to possible path restrictions in the blocks.
=> Use referencewidget to solve bug with event-listingblock

docs/HISTORY.txt, ftw/events/browser/templates/mopage_events.pt, setup.py
When using the variable name "attrs", chameleon does no longer evaluate the expression.
=> Fix chameleon support for mopage export.

docs/HISTORY.txt, ftw/events/behaviors/location.py, ftw/events/contents/eventpage.py, ftw/events/tests/test_event_listing.py, ftw/events/tests/test_mopage_export.py
This way the field won't get formatted incorrectly in the edit form.
=> Use an integer field for the value of the zip code.

docs/HISTORY.txt, ftw/events/resources/events-theming.scss
The text should not be set to hidden by the ftw.events package.
This behavior should be done in a theme or policy package.
=> Display action text next to icon

docs/HISTORY.txt, ftw/events/upgrades/20170119084718_convert_filter_by_path_references/upgrade.py
The upgrade step converts "filter_by_path" references of the event listing blocks.
In version 1.2.0 (see https://github.com/4teamwork/ftw.events/pull/17) the references of the "filter_by_path" field of the event listing block has been changed from "ObjPathSourceBinder" to "PathSourceBinder". Event listing blocks created before 1.2.0 still hold objects which need to be converted to paths.
=> Add missing upgrade step from 1.2.0

docs/HISTORY.txt, ftw/events/profiles/default/tinymce.xml
Makes `EventPage` and `EventFodler` linkable in TinyMCE.
Do no include upgrade step, since this could change existing projects.
closes #22
=> Make Events linkable in TinyMCE editor.

docs/HISTORY.txt, ftw/events/browser/eventlistingblock.py, ftw/events/tests/test_event_listing.py, ftw/events/tests/test_event_listingblock.py, ftw/events/tests/utils.py
Inactive event pages will now be shown in the event listing view (and thus the event listing block) if the user has the permission to add event pages..
Important: the event pages will only be shown if event pages from a single container are shown. Otherwise a user could trick the system and be able to see inactive event pages from a path where he does not have the permission to add events.
=> Show inactive events if the user has the permission to add events.

docs/HISTORY.txt, ftw/events/browser/eventlistingblock.py, ftw/events/browser/templates/eventlistingblock.pt, ftw/events/contents/eventlistingblock.py, ftw/events/locales/de/LC_MESSAGES/ftw.events.po, ftw/events/locales/ftw.events.pot, ftw/events/resources/events-theming.scss, ftw/events/tests/test_event_listingblock.py, setup.py
This option makes use of a feature in "ftw.simplelayout" where a block can be hidden visually.
=> Add option to hide an empty listing block.

docs/HISTORY.txt, ftw/events/browser/eventlistingblock.py
This has only been noticed once it has been installed on the production server where Solr is installed (Solr is not installed in the tests).
=> Fix rendering of inactive event pages.

docs/HISTORY.txt, ftw/events/browser/eventlisting.py, ftw/events/browser/eventlistingblock.py, ftw/events/tests/test_event_listing.py, ftw/events/tests/test_event_listingblock.py, ftw/events/tests/test_ics_view.py
Before the result on the listing view after clicking on the "Show further event" was completely different.
=> Respect `exclude_past_events` setting of block, also on the event listing view

docs/HISTORY.txt, ftw/events/contents/eventlistingblock.py, ftw/events/testing.py
The contentree source does not work with ftw.referencewidget.
IMPORTANT: I hat to implement my own filter class, which actually does not filter anything.
Since the default filter requires a object, but since a it is a list (not RelationList) the converter returns
a list of strings instead.
=> Use ReferenceObjSourceBinder for filter by path field in eventlistingblock

docs/HISTORY.txt, ftw/events/contents/eventlistingblock.py, ftw/events/locales/de/LC_MESSAGES/ftw.events.po, ftw/events/locales/ftw.events.pot
The list of configuration options on the event listing block grew quite long.
Separating the fields into fieldset should provide a better user experience.
=> Group fields of the event listing block.

docs/HISTORY.txt, setup.py
Since `testing.py` of ftw.events depends on `collective.taskqueue` we should add it to the test-dependencies.
I had to add it to the dependencies in another project because I wanted to use the builders.
=> Add collective.taskqueue to test dependencies

docs/HISTORY.txt, ftw/events/browser/configure.zcml, ftw/events/browser/eventlisting.py, ftw/events/browser/eventlistingblock.py, ftw/events/browser/templates/eventlistingblock.pt, ftw/events/browser/templates/events_rss.pt, ftw/events/contents/eventlistingblock.py, ftw/events/locales/de/LC_MESSAGES/ftw.events.po, ftw/events/locales/ftw.events.pot, ftw/events/resources/events-theming.scss, ftw/events/tests/test_rss_view.py
Implement a new view `events_rss` which shows an rss feed of current events on the event listing block.
Now there is an option on the newslisting block to show the link to the rss feed.
closes #29
=> Implement RSS feed for events

docs/HISTORY.txt, ftw/events/browser/configure.zcml, ftw/events/locales/de/LC_MESSAGES/ftw.events.po, ftw/events/locales/ftw.events.pot, ftw/events/profiles/default/actions.xml, ftw/events/tests/test_ics_view.py, ftw/events/upgrades/20181031165317_add_object_action_for_exporting_ics_file/actions.xml, ftw/events/upgrades/20181031165317_add_object_action_for_exporting_ics_file/upgrade.py
This allows a user to download an ics file of all the events within the event folder.
=> Enable "ics_view" on event folder.

docs/HISTORY.txt, ftw/events/resources/events-theming.scss
To create a similar appearance as in ftw.news this change adds
an arrow in front of the 'more'-button as there i one in front
of it in ftw.news.
=> Add arrow to 'more'-button

docs/HISTORY.txt, ftw/events/portlets/events_archive_portlet.py, ftw/events/portlets/templates/events_archive_portlet.pt, ftw/events/resources/event-archive-portlet.js, ftw/events/resources/event-archive-portlet.scss, ftw/events/tests/test_event_archive_portlets.py
The functionality of the event archive portlet was copied from the news archive portlet. The html classes in both (ftw.news and ftw.events) were the same which meant that when ftw.news was installed next to ftw.events, both javascripts acted on both archive portlets. This had the effect that on click, the collapsible months were opened and immediately closed again.
By adding unique classes the news archive portlet javascript will not act on the event archive portlet anymore.
=> Fix event archive portlet compatibility with ftw.news

docs/HISTORY.txt, ftw/events/locales/de/LC_MESSAGES/ftw.events.po
@maethu Do you see any other typos, I think this is only one.
=> Fix typo in "Veranstalgungsauflistung" => "Veranstaltungsauflistung"

docs/HISTORY.txt, ftw/events/browser/eventlisting.py
The next events shall be on top not the one furthest away in the future
=> Change sort order to match the same the EventListingBlock

docs/HISTORY.txt, ftw/events/browser/configure.zcml, ftw/events/browser/event_accessor.py, ftw/events/tests/test_ics_view.py
The event accessor implementation could not get the location of the `ftw.event.EventPage` events, because it did not use the same behaviour for the location as our EventPage. 
To fix this we adapt the event accessor ourselves. To get this to work we must use the events schema for the adapter because it higher up in the order than the default interface for the event accessor (`IDXEvent`) provided by the event, whereas the `IEventPage` is lower and so cannot be used.
With this fix everywhere the location is called via the event accessor the right location is not returned. This can be seen eg. in the ICS export and so we also tested it right there.
=> Fix event accessor location (eg. ics export now includes location)

ftw/events/tests/builders.py, ftw/events/tests/test_staging.py
**Situation**
`plone.app.events` replaces the timezone with a fake when setting `start` and `end`, without recalculating the DateTime to `UTC`. Because it has an own timezone field where the timezone is saved, it saves the `start` and `end` wrongly if it is given with a timezone other than the timezone set on the timezone field.
The getter for `start` and `end` however recalculates the DateTime with the timezone saved on the object. This means that the getter will return a different time than what the setter as been given to. Eg.:
```python
from plone.app.event.dx.behaviors import IEventBasic
from datetime import datetime
from pytz import timezone
from plone.event.utils import pydt
context.timezone = 'Europe/Zurich'
behaviour = IEventBasic(context)
start_date = pydt(datetime(2019, 1, 1, …
```
=> Add test for plone.app.event staging behaviour

docs/HISTORY.txt, ftw/events/hooks.py
In case of a "reinstall", this is for example not necessary.
=> Improve reindex_indexes install hook - to not reindex if not necessary.

docs/HISTORY.txt, setup.py, test-plone-4.3.x.cfg
p.a.referenceablebehavior is not compatible with plone 5 and breaks
stuff when it is used. It was not used in here anymore but with
ftw.events we installed it and if another package falsely still used it,
it broke the installation.
=> Only install p.a.referenceablebehavior on Plone 4 with a "plone4" extra

docs/HISTORY.txt, ftw/events/browser/eventlisting.py, ftw/events/browser/templates/events_rss.pt, ftw/events/tests/test_rss_view.py
Example output:
```xml
<rss xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:atom="http://www.w3.org/2005/Atom" version="2.0">
<channel>
<atom:link rel="self" type="application/rss+xml" href="http://localhost:8080/Plone1/events-1/veranstaltungen/events_rss"/>
<title>Veranstaltungen</title>
<link>http://localhost:8080/Plone1/events-1/veranstaltungen/events_rss</link>
<description>Veranstaltungen - Veranstaltungs Feed</description>
<item>
<title>Ein Event</title>
<link>http://localhost:8080/Plone1/events-1/ein-event</link>
<description/>
<guid>http://localhost:8080/Plone1/events-1/ein-event</guid>
<lastBuildDate>Wed, 02 Sep 2020 09:17:31 +0200</lastBuildDate>
<pubDate>Tue, 01 Sep 2020 09:00:00 +0200</pubDate>
<dc:subject> üüüüüü </dc:subject>
<dc:subject> tag1 </dc:subject>
<dc:subject> …
```
=> Add more info to rss feed and use Event start date as pubDate.

docs/HISTORY.txt, ftw/events/tests/test_event_folder.py, ftw/events/tests/test_mopage_export.py, ftw/events/viewlets/rsslink.py
Before the syndication links in the html head were rendered anyway regardless of the configuration, which lead to a "NotFound" if actually followed that link.
=> Respect syndications settings on EventFolder RSS viewlet.
